# BetterChat Made by _nitey
# Paper 1.19.2
# Discord : .rosed

############################################################
# +------------------------------------------------------+ #
# |              BetterChat Proximity Chat               | #
# +------------------------------------------------------+ #
############################################################

# Radius of proximity chat
proximity-radius: 10

# Proximity radius after holding a megaphone
megaphone-proximity-radius: 20